server:
  error:
    include-message: 'always'
spring:
  application:
    name: 'graph-svc'
  neo4j:
    uri: ${N4J_URI}
    authentication: 
      username: ${N4J_USERNAME}
      password: ${N4J_INSTANCE_PASS} 
  data:
    redis:
      url: ${REDISCLOUD_URL}
springdoc:
  api-docs:
    path: /api
