spring:
  application:
    name: 'graph-svc'
  neo4j:
    uri: 'neo4j+s://5203e0d8.databases.neo4j.io'
    authentication: 
      username: 'neo4j'
      password: ${N4J_Pass} 
springdoc:
  api-docs:
    path: /api
