server:
  error:
    include-message: 'always'
spring:
  application:
    name: 'graph-svc'
  neo4j:
    uri: ${N4J_URI}
    authentication: 
      username: ${N4J_USERNAME}
      password: ${N4J_INSTANCE_PASS} 
  data:
    redis:
      url: ${REDISCLOUD_URL}
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         keycloak:
  #           client-id: kob-kbs
  #           client-secret: ${KC_CLIENT_SECRET}
  #           authorization-grant-type: authorization_code
  #           scope: openid
  #       provider:
  #         keycloak:
  #           issuer-uri: http://localhost:8080/realms/spring-boot
  #           user-name-attribute: preferred_username
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:8080/realms/spring-boot
springdoc:
  api-docs:
    path: /api
